#!/usr/bin/env python

import os
import sys
import imp

from distutils.spawn import find_executable


def usage():
    print 'usage: %s <knock_str> <command> [arg1 arg2 ... argN]' % sys.argv[0]
    exit(-1)

if __name__ == '__main__':

    if len(sys.argv) < 3:
        usage()

    if 'darwin' in sys.platform:
        os.environ['DYLD_INSERT_LIBRARIES'] = imp.find_module('libknock')[1]
        os.environ['DYLD_FORCE_FLAT_NAMESPACE'] = '1'
    if 'linux' in sys.platform:
        os.environ['LD_PRELOAD'] = imp.find_module('libknock')[1]
    os.environ['OOBRE_KNOCK'] = sys.argv[1].encode('hex')
    cmds = [find_executable(sys.argv[2])]
    cmds.extend(sys.argv[3:])
    try:
        os.execve(cmds[0], cmds, os.environ)
    except Exception, e:
        print 'Exception encountered: %s' % e
        usage()
